diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
gui.recentrepo=C:/Users/frizz/OneDrive/Latex/PhysicsBowl-MindMap
user.name=tian2-ai
user.email=frizzletsh@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.pbmp.url=https://github.com/rabbittsh/PhysicsBowl-Mindmap.git
remote.pbmp.fetch=+refs/heads/*:refs/remotes/pbmp/*
remote.origin.url=https://github.com/rabbittsh/PhysicsBowl-Mindmap.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.main.remote=origin
branch.main.merge=refs/heads/main
gui.wmstate=normal
gui.geometry=1057x651+332+270 189 100
